import type { SignalDefinition } from "./definition";

/**
 * The 13 LIVE signal definitions, transcribed VERBATIM from Signal Catalog v0.3.
 * Do not invent, extend, or alter. New signals come from a catalog revision only.
 */
export const LIVE_SIGNAL_DEFINITIONS: SignalDefinition[] = [
  { id: "feed-diversity", display_name: "Feed Concentration", catalog_category: "Feed & Algorithm", governance_category: "content_exposure", domain: "social", supported_platforms: ["instagram", "tiktok", "youtube"], value_type: "scalar", unit: "%", inverted: false, green_cut: 40, yellow_cut: 60, band_labels: { aligned: "Top creator <=40% of views", attention: "40-60%", crossed: ">60%" }, data_source_path: "contentConsumed.byOwner", min_data: {}, tier: null, lifecycle: "live" },
  { id: "algorithmic-amplification", display_name: "Algorithm Influence", catalog_category: "Feed & Algorithm", governance_category: "content_exposure", domain: "social", supported_platforms: ["instagram", "tiktok", "youtube"], value_type: "scalar", unit: "%", inverted: false, green_cut: 30, yellow_cut: 50, band_labels: { aligned: "<=30% from unfollowed", attention: "30-50%", crossed: ">50%" }, data_source_path: "contentConsumed.byOwner vs following.accounts", min_data: {}, tier: null, lifecycle: "live" },
  { id: "follow-feed-alignment", display_name: "Follow-to-Feed Gap", catalog_category: "Feed & Algorithm", governance_category: "social_interaction", domain: "social", supported_platforms: ["instagram", "tiktok"], value_type: "scalar", unit: "%", inverted: true, green_cut: 50, yellow_cut: 25, band_labels: { aligned: ">=50% of followed appear", attention: "25-50%", crossed: "<25%" }, data_source_path: "following.accounts vs contentConsumed.byOwner", min_data: { following: 5 }, tier: null, lifecycle: "live" },
  { id: "content-volume", display_name: "Content Volume", catalog_category: "Activity & Time", governance_category: "attention_engagement", domain: "wellness", supported_platforms: ["instagram", "tiktok", "youtube", "facebook"], value_type: "scalar", unit: "count", inverted: false, green_cut: 50, yellow_cut: 100, band_labels: { aligned: "<=50 items", attention: "50-100 items", crossed: ">100 items" }, data_source_path: "contentConsumed.total", min_data: {}, tier: null, lifecycle: "live" },
  { id: "video-ratio", display_name: "Short-Form Video", catalog_category: "Content & Creation", governance_category: "content_exposure", domain: "social", supported_platforms: ["instagram", "tiktok", "youtube", "facebook"], value_type: "scalar", unit: "%", inverted: false, green_cut: 70, yellow_cut: 90, band_labels: { aligned: "<=70% video", attention: "70-90%", crossed: ">90%" }, data_source_path: "contentConsumed.videoCount / total", min_data: {}, tier: null, lifecycle: "live" },
  { id: "late-night-activity", display_name: "Late-Night Activity", catalog_category: "Activity & Time", governance_category: "attention_engagement", domain: "wellness", supported_platforms: ["instagram", "tiktok", "youtube"], value_type: "scalar", unit: "%", inverted: false, green_cut: 15, yellow_cut: 30, band_labels: { aligned: "<=15% after 9pm", attention: "15-30%", crossed: ">30%" }, data_source_path: "hourlyDistribution (21-23, 0-5)", min_data: {}, tier: null, lifecycle: "live" },
  { id: "screen-time-distribution", display_name: "Screen-Time Distribution", catalog_category: "Activity & Time", governance_category: "attention_engagement", domain: "wellness", supported_platforms: ["instagram", "tiktok", "youtube"], value_type: "scalar", unit: "%", inverted: false, green_cut: 60, yellow_cut: 80, band_labels: { aligned: "<60% in one period", attention: "60-80%", crossed: ">80%" }, data_source_path: "hourlyDistribution -> periodDistribution", min_data: {}, tier: null, lifecycle: "live" },
  { id: "new-contacts", display_name: "New Contacts", catalog_category: "Social & Connections", governance_category: "social_interaction", domain: "social", supported_platforms: ["instagram", "tiktok"], value_type: "scalar", unit: "count", inverted: false, green_cut: 5, yellow_cut: 15, band_labels: { aligned: "<=5 new in 30 days", attention: "5-15 new", crossed: ">15 new" }, data_source_path: "following.accounts[].followedAt (recent 30 days)", min_data: {}, tier: null, lifecycle: "live" },
  { id: "search-behavior", display_name: "Search Activity", catalog_category: "Discovery & Interests", governance_category: "content_exposure", domain: "social", supported_platforms: ["instagram", "tiktok", "youtube", "facebook"], value_type: "scalar", unit: "count", inverted: false, green_cut: 5, yellow_cut: 20, band_labels: { aligned: "<=5 searches", attention: "5-20 searches", crossed: ">20 searches" }, data_source_path: "searches.total", min_data: {}, tier: null, lifecycle: "live" },
  { id: "binge-sessions", display_name: "Compulsive Consumption", catalog_category: "Activity & Time", governance_category: "attention_engagement", domain: "wellness", supported_platforms: ["instagram", "tiktok", "youtube"], value_type: "scalar", unit: "count", inverted: false, green_cut: 30, yellow_cut: 50, band_labels: { aligned: "Longest session <=30 items", attention: "30-50 items", crossed: ">50 items" }, data_source_path: "contentTimeline[] (ordered timestamps)", min_data: { contentTimeline: 2 }, tier: null, lifecycle: "live" },
  { id: "pause-ratio", display_name: "Recovery Gaps", catalog_category: "Activity & Time", governance_category: "wellness", domain: "wellness", supported_platforms: ["instagram", "tiktok", "youtube"], value_type: "scalar", unit: "%", inverted: true, green_cut: 40, yellow_cut: 20, band_labels: { aligned: ">=40% sessions have breaks", attention: "20-40%", crossed: "<20%" }, data_source_path: "contentTimeline[] (gaps within sessions)", min_data: { contentTimeline: 2 }, tier: null, lifecycle: "live" },
  { id: "rabbit-hole-depth", display_name: "Rabbit-Hole Depth", catalog_category: "Feed & Algorithm", governance_category: "content_exposure", domain: "social", supported_platforms: ["instagram", "tiktok", "youtube"], value_type: "scalar", unit: "count", inverted: false, green_cut: 5, yellow_cut: 10, band_labels: { aligned: "Max run <=5 same-creator", attention: "5-10 consecutive", crossed: ">10 consecutive" }, data_source_path: "contentTimeline[].owner (consecutive same-owner runs)", min_data: {}, tier: null, lifecycle: "live" },
  { id: "interest-diversity", display_name: "Interest Diversity", catalog_category: "Discovery & Interests", governance_category: "content_exposure", domain: "social", supported_platforms: ["instagram", "tiktok", "youtube", "facebook"], value_type: "scalar", unit: "ratio", inverted: true, green_cut: 0.30, yellow_cut: 0.15, band_labels: { aligned: "Ratio >=0.30", attention: "0.15-0.30", crossed: "<0.15" }, data_source_path: "contentTimeline unique owners / total items", min_data: { items: 5, byOwner: 1 }, tier: null, lifecycle: "live" },
];

export const LIVE_SIGNAL_DEFINITION_BY_ID: Record<string, SignalDefinition> =
  Object.fromEntries(LIVE_SIGNAL_DEFINITIONS.map((d) => [d.id, d]));
